# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: arXiv-daily-ai-enhanced

on:
  schedule:
    - cron: "30 16 * * *"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync
    - name: Run script
      run: |
        source .venv/bin/activate
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        export OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
        export LANGUAGE="${{ vars.LANGUAGE }}"
        export CATEGORIES="${{ vars.CATEGORIES }}"
        export MODEL_NAME="${{ vars.MODEL_NAME }}"
        bash run.sh
    - name: commit
      run: |
        git config --global user.email "${{ vars.EMAIL }}"
        git config --global user.name "${{ vars.NAME }}"
        git add .
        # 检查是否有变更需要提交
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "update"
    - name: Pull latest changes and push
      run: |
        # 设置Git配置以处理自动合并
        git config pull.rebase true
        git config rebase.autoStash true
        
        # 尝试推送，如果失败则拉取并重试
        for i in {1..3}; do
          echo "Push attempt $i"
          if git push origin main; then
            echo "Push successful"
            break
          else
            echo "Push failed, pulling latest changes..."
            git pull origin main --no-edit || true
            if [ $i -eq 3 ]; then
              echo "Failed to push after 3 attempts"
              exit 1
            fi
          fi
        done
    - name: Check Email Configuration
      run: |
        if [ -z "${{ vars.NOTIFICATION_EMAIL }}" ]; then
          echo "⚠️ Email notification is not configured. Skipping email sending."
          echo "To enable email notifications, please set NOTIFICATION_EMAIL variable and SMTP secrets."
        else
          echo "✅ Email notification is configured for: ${{ vars.NOTIFICATION_EMAIL }}"
        fi
    - name: Set Date Environment Variable
      if: success() && vars.NOTIFICATION_EMAIL != ''
      continue-on-error: true
      run: echo "TODAY=$(date -u '+%Y-%m-%d')" >> $GITHUB_ENV
    - name: Send Email Notification
      if: success() && vars.NOTIFICATION_EMAIL != ''
      continue-on-error: true
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "📚 Daily arXiv AI Enhanced - ${{ env.TODAY }}"
        to: ${{ vars.NOTIFICATION_EMAIL }}
        from: ${{ secrets.SMTP_USERNAME }}
        body: |
          🎉 今日 arXiv 论文已更新完成！
          
          📅 日期: ${{ env.TODAY }}
          🔗 查看地址: https://github.com/${{ github.repository }}
          📂 数据文件: https://github.com/${{ github.repository }}/blob/main/data/${{ env.TODAY }}.md
          
          📊 本次更新包含以下类别:
          - ${{ vars.CATEGORIES }}
          
          🤖 使用模型: ${{ vars.MODEL_NAME }}
          🌐 语言: ${{ vars.LANGUAGE }}
          
          ---
          此邮件由 GitHub Actions 自动发送
        html_body: |
          <h2>📚 Daily arXiv AI Enhanced</h2>
          <p><strong>📅 日期:</strong> ${{ env.TODAY }}</p>
          <p><strong>🔗 查看地址:</strong> <a href="https://github.com/${{ github.repository }}">GitHub Repository</a></p>
          <p><strong>📂 数据文件:</strong> <a href="https://github.com/${{ github.repository }}/blob/main/data/${{ env.TODAY }}.md">今日论文摘要</a></p>
          
          <h3>📊 更新信息</h3>
          <ul>
            <li><strong>类别:</strong> ${{ vars.CATEGORIES }}</li>
            <li><strong>模型:</strong> ${{ vars.MODEL_NAME }}</li>
            <li><strong>语言:</strong> ${{ vars.LANGUAGE }}</li>
          </ul>
          
          <hr>
          <p><small>此邮件由 GitHub Actions 自动发送</small></p>
